// Client-side PDF statement/bill. Saved via normal browser download (goes to the phone's Downloads folder).
type P = { name: string; phone?: string | null; kind: string; balance: number };
type E = { amount: number; direction: "gave" | "got"; entry_date: string; note?: string | null };

const rs = (n: number) => "Rs. " + Math.abs(n).toLocaleString("en-IN", { maximumFractionDigits: 2 });

export async function downloadStatement(party: P, entries: E[], business?: string | null) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  const W = doc.internal.pageSize.getWidth();
  doc.setFillColor(31, 77, 61);
  doc.rect(0, 0, W, 28, "F");
  doc.setTextColor(255);
  doc.setFontSize(16);
  doc.text(business || "LenaDena", 14, 13);
  doc.setFontSize(10);
  doc.text("Account Statement / Bill", 14, 21);
  doc.text(new Date().toLocaleString("en-IN"), W - 14, 21, { align: "right" });
  doc.setTextColor(0);
  doc.setFontSize(12);
  doc.text(`${party.name}${party.phone ? "  ·  " + party.phone : ""}`, 14, 38);
  doc.setFontSize(10);
  doc.text(`Type: ${party.kind}`, 14, 44);

  let y = 56;
  const head = () => {
    doc.setFont("helvetica", "bold");
    doc.text("Date", 14, y); doc.text("Note", 44, y);
    doc.text("Gave", 130, y, { align: "right" }); doc.text("Got", 160, y, { align: "right" });
    doc.text("Balance", W - 14, y, { align: "right" });
    doc.setFont("helvetica", "normal");
    doc.line(14, y + 2, W - 14, y + 2);
    y += 8;
  };
  head();
  let run = 0, gave = 0, got = 0;
  for (const e of entries) {
    run += e.direction === "gave" ? e.amount : -e.amount;
    if (e.direction === "gave") gave += e.amount; else got += e.amount;
    if (y > 275) { doc.addPage(); y = 20; head(); }
    doc.text(new Date(e.entry_date).toLocaleDateString("en-IN"), 14, y);
    doc.text((e.note ?? "").slice(0, 40), 44, y);
    if (e.direction === "gave") doc.text(rs(e.amount), 130, y, { align: "right" });
    else doc.text(rs(e.amount), 160, y, { align: "right" });
    doc.text(rs(run) + (run > 0 ? " Dr" : run < 0 ? " Cr" : ""), W - 14, y, { align: "right" });
    y += 7;
  }
  doc.line(14, y, W - 14, y);
  y += 8;
  doc.setFont("helvetica", "bold");
  doc.text(`Total gave: ${rs(gave)}    Total got: ${rs(got)}`, 14, y);
  y += 8;
  const b = party.balance;
  doc.text(b > 0 ? `Balance to receive: ${rs(b)}` : b < 0 ? `Balance to pay: ${rs(b)}` : "Settled — no balance due", 14, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Generated by LenaDena — Digital Khata", W / 2, 290, { align: "center" });
  doc.save(`${party.name.replace(/[^\w]+/g, "_")}_statement.pdf`);
}
